### Login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "leanhvu123",
    "password": "leanhvu"
}

### Register
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "name": "Lê Anh Vũ",
    "age": 23,
    "gender": "Nam",
    "phone": "0987654344",
    "email": "leanhvu123@gmail.com",
    "username": "leanhvu123",
    "password": "leanhvu"
}
